name: release

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Release
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if [[ "${GITHUB_REF#refs/*/}" == *"-rc"* ]]; then
          gh release create "${GITHUB_REF#refs/*/}" --prerelease --title=$tag --generate-notes
        else
          gh release create "${GITHUB_REF#refs/*/}" --title=$tag --generate-notes
        fi

